#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#install.packages("remotes")
#BiocManager::install(version = "3.9",ask=FALSE)
#BiocManager::install(version="3.9", update=TRUE, ask=FALSE)
install.packages("missForest")
BiocManager::install("biomaRt")
install.packages("glmnet")
install.packages("caret")
#install.packages("tidyverse")
#install.packages("optparse")
install.packages("doParallel")

